# -*- coding: utf-8 -*-
"""High_Confidence_Errors_FLAN_T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JofPIilvtUAg2E_MfC43OtlqfYzuRxPY
"""

!pip install -q transformers torch scikit-learn pandas numpy tqdm matplotlib sentence-transformers scipy

# Import Libraries
# Purpose: Load core Python, ML, and visualization tools.
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.stats import pearsonr, spearmanr

# Device Configuration
# Purpose: Detect CPU/GPU for reproducibility.
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# Load FLAN-T5-Base
# Purpose: Load an open-source, instruction-tuned LLM

MODEL_NAME = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

model.to(device)
model.eval()

# Text Generation Function
# Purpose: Generate stochastic model outputs for uncertainty analysis.

def generate_answer(prompt, temperature=0.7, max_tokens=128):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True).to(device)
    outputs = model.generate(
        **inputs,
        do_sample=True,
        temperature=temperature,
        max_new_tokens=max_tokens
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Self-Consistency Sampling
# Purpose: Generate multiple answers per question.

def self_consistency(prompt, runs=7):
    return [generate_answer(prompt) for _ in range(runs)]

# Syntactic Confidence Score
# Purpose: Estimate confidence using answer agreement.

def confidence_score(answers):
    unique_answers = len(set(answers))
    return 1 - (unique_answers / len(answers))

# Load Sentence Embedding Model
# Purpose: Enable semantic similarity analysis.

embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Semantic Confidence Score
# Purpose: Measure agreement based on meaning, not wording.

def semantic_confidence(answers):
    embeddings = embedder.encode(answers)
    sim_matrix = cosine_similarity(embeddings)
    upper_triangle = sim_matrix[np.triu_indices(len(answers), k=1)]
    return upper_triangle.mean()

dataset = [

# =========================
# 1. FACTUAL KNOWLEDGE (25)
# =========================
{"question": "Is Nigeria a member of the African Union?", "ground_truth": "Yes"},
{"question": "Is the capital of France Paris?", "ground_truth": "Yes"},
{"question": "Is water composed of hydrogen and oxygen?", "ground_truth": "Yes"},
{"question": "Is the sun a star?", "ground_truth": "Yes"},
{"question": "Is the Great Wall of China visible from space with the naked eye?", "ground_truth": "No"},
{"question": "Is Mount Everest the tallest mountain above sea level?", "ground_truth": "Yes"},
{"question": "Is Python a compiled programming language?", "ground_truth": "No"},
{"question": "Does the Earth revolve around the Sun?", "ground_truth": "Yes"},
{"question": "Is the human heart located on the right side of the chest?", "ground_truth": "No"},
{"question": "Is electricity measured in volts?", "ground_truth": "Yes"},
{"question": "Is oxygen heavier than nitrogen?", "ground_truth": "Yes"},
{"question": "Is Africa the largest continent by land area?", "ground_truth": "No"},
{"question": "Is the speed of light constant in a vacuum?", "ground_truth": "Yes"},
{"question": "Is gold a chemical element?", "ground_truth": "Yes"},
{"question": "Is Pluto classified as a planet?", "ground_truth": "No"},
{"question": "Is photosynthesis performed by animals?", "ground_truth": "No"},
{"question": "Is the Nile River the longest river in the world?", "ground_truth": "Yes"},
{"question": "Is the human genome made of DNA?", "ground_truth": "Yes"},
{"question": "Is the boiling point of water 100°C at sea level?", "ground_truth": "Yes"},
{"question": "Is sound able to travel through a vacuum?", "ground_truth": "No"},
{"question": "Is the Moon larger than Earth?", "ground_truth": "No"},
{"question": "Is iron a metal?", "ground_truth": "Yes"},
{"question": "Is the Pacific Ocean the largest ocean?", "ground_truth": "Yes"},
{"question": "Is gravity weaker on the Moon than on Earth?", "ground_truth": "Yes"},
{"question": "Is the human brain part of the central nervous system?", "ground_truth": "Yes"},

# =========================
# 2. LOGICAL / REASONING (25)
# =========================
{"question": "If all birds can fly and a penguin is a bird, can a penguin fly?", "ground_truth": "No"},
{"question": "If it is raining, does that guarantee the ground is wet?", "ground_truth": "Yes"},
{"question": "If A is greater than B and B is greater than C, is A greater than C?", "ground_truth": "Yes"},
{"question": "If a person is older than 18, are they necessarily retired?", "ground_truth": "No"},
{"question": "If two numbers are both even, is their sum even?", "ground_truth": "Yes"},
{"question": "If a statement is false, is its negation true?", "ground_truth": "Yes"},
{"question": "If someone lives in Africa, do they necessarily live in Nigeria?", "ground_truth": "No"},
{"question": "If today is Monday, is tomorrow Wednesday?", "ground_truth": "No"},
{"question": "If all mammals are animals, are all animals mammals?", "ground_truth": "No"},
{"question": "If a light is switched off, is the room necessarily dark?", "ground_truth": "No"},
{"question": "If a product costs more, is it always higher quality?", "ground_truth": "No"},
{"question": "If a number is divisible by 4, is it divisible by 2?", "ground_truth": "Yes"},
{"question": "If a car has no fuel, can it drive?", "ground_truth": "No"},
{"question": "If someone is sleeping, are they awake?", "ground_truth": "No"},
{"question": "If a triangle has three equal sides, is it equilateral?", "ground_truth": "Yes"},
{"question": "If a person is hungry, have they eaten recently?", "ground_truth": "No"},
{"question": "If all squares are rectangles, are all rectangles squares?", "ground_truth": "No"},
{"question": "If an exam is difficult, will everyone fail?", "ground_truth": "No"},
{"question": "If an object floats, is it necessarily light?", "ground_truth": "No"},
{"question": "If the power is out, can electronic devices operate normally?", "ground_truth": "No"},
{"question": "If a number is prime, is it divisible only by 1 and itself?", "ground_truth": "Yes"},
{"question": "If someone owns a car, can they necessarily drive?", "ground_truth": "No"},
{"question": "If a statement is true, can it also be false?", "ground_truth": "No"},
{"question": "If a medicine works for one person, will it work for all?", "ground_truth": "No"},
{"question": "If ice melts, does it become liquid water?", "ground_truth": "Yes"},

# =========================
# 3. POLICY / RULE-BASED (25)
# =========================
{"question": "Can a loan be approved if the borrower defaulted in the last 6 months?", "ground_truth": "No"},
{"question": "Is a passport required for international travel?", "ground_truth": "Yes"},
{"question": "Can a minor legally sign a binding contract?", "ground_truth": "No"},
{"question": "Is wearing a seatbelt legally required in many countries?", "ground_truth": "Yes"},
{"question": "Can someone vote without being a citizen?", "ground_truth": "No"},
{"question": "Is tax payment mandatory for employed individuals in most countries?", "ground_truth": "Yes"},
{"question": "Can a company operate without registration?", "ground_truth": "No"},
{"question": "Is driving under the influence of alcohol legal?", "ground_truth": "No"},
{"question": "Can an employee be paid below minimum wage legally?", "ground_truth": "No"},
{"question": "Is data protection required when handling personal data?", "ground_truth": "Yes"},
{"question": "Can a bank open an account without identity verification?", "ground_truth": "No"},
{"question": "Is child labor permitted under labor laws?", "ground_truth": "No"},
{"question": "Can a court verdict be appealed?", "ground_truth": "Yes"},
{"question": "Is insurance mandatory for motor vehicles in many countries?", "ground_truth": "Yes"},
{"question": "Can a student be expelled for academic misconduct?", "ground_truth": "Yes"},
{"question": "Is bribery legal in public office?", "ground_truth": "No"},
{"question": "Can a visa expire?", "ground_truth": "Yes"},
{"question": "Is consent required before collecting personal data?", "ground_truth": "Yes"},
{"question": "Can a contract be enforced if signed under duress?", "ground_truth": "No"},
{"question": "Is plagiarism acceptable in academic work?", "ground_truth": "No"},
{"question": "Can intellectual property be legally protected?", "ground_truth": "Yes"},
{"question": "Is fraud considered a criminal offense?", "ground_truth": "Yes"},
{"question": "Can a minor obtain a driver’s license?", "ground_truth": "No"},
{"question": "Is freedom of speech unlimited in all jurisdictions?", "ground_truth": "No"},
{"question": "Can laws change over time?", "ground_truth": "Yes"},

# =========================
# 4. ECONOMIC / CONCEPTUAL (25)
# =========================
{"question": "Does inflation reduce purchasing power?", "ground_truth": "Yes"},
{"question": "Can interest rates be negative?", "ground_truth": "Yes"},
{"question": "Does higher demand generally increase prices?", "ground_truth": "Yes"},
{"question": "Is scarcity a fundamental economic concept?", "ground_truth": "Yes"},
{"question": "Does saving money always increase wealth?", "ground_truth": "No"},
{"question": "Is unemployment measured as a percentage of the labor force?", "ground_truth": "Yes"},
{"question": "Does diversification reduce investment risk?", "ground_truth": "Yes"},
{"question": "Is GDP a measure of economic output?", "ground_truth": "Yes"},
{"question": "Does a budget deficit mean government revenue exceeds spending?", "ground_truth": "No"},
{"question": "Is opportunity cost the value of the next best alternative?", "ground_truth": "Yes"},
{"question": "Can inflation occur without economic growth?", "ground_truth": "Yes"},
{"question": "Does monopoly reduce market competition?", "ground_truth": "Yes"},
{"question": "Is supply independent of price?", "ground_truth": "No"},
{"question": "Can taxes influence consumer behavior?", "ground_truth": "Yes"},
{"question": "Is money neutral in the short run?", "ground_truth": "No"},
{"question": "Does economic recession imply negative growth?", "ground_truth": "Yes"},
{"question": "Is a higher interest rate likely to reduce borrowing?", "ground_truth": "Yes"},
{"question": "Does price elasticity measure responsiveness to price changes?", "ground_truth": "Yes"},
{"question": "Is trade beneficial to all parties involved?", "ground_truth": "No"},
{"question": "Can government spending stimulate an economy?", "ground_truth": "Yes"},
{"question": "Does inflation always harm the economy?", "ground_truth": "No"},
{"question": "Is profit equal to revenue minus cost?", "ground_truth": "Yes"},
{"question": "Can a currency depreciate?", "ground_truth": "Yes"},
{"question": "Is economic growth evenly distributed?", "ground_truth": "No"},
{"question": "Does productivity growth increase long-term output?", "ground_truth": "Yes"}
]

len(dataset)

# Full Experiment
# Purpose: Collect predictions, confidence, and correctness.

results = []

for item in tqdm(dataset):
    question = item["question"]
    gt = item["ground_truth"]

    answers = self_consistency(question)
    final_answer = answers[0]

    results.append({
        "question": question,
        "ground_truth": gt,
        "final_answer": final_answer,
        "confidence_sc": confidence_score(answers),
        "confidence_semantic": semantic_confidence(answers),
        "correct": int(gt.lower() in final_answer.lower()),
        "all_answers": answers
    })

df = pd.DataFrame(results)
df.head(1)

# Add Category Labels
# Purpose: Enable per-category failure analysis.

categories = (
    ["Factual"] * 25 +
    ["Logical"] * 25 +
    ["Policy"] * 25 +
    ["Economic"] * 25
)

df["category"] = categories
df.head()

# Basic Accuracy Metrics
# Purpose: High-level performance overview.

df["correct"].mean()

# Correlation Analysis
# Purpose: Test alignment between confidence and correctness.

pearson_sc = pearsonr(df["confidence_sc"], df["correct"])
pearson_sem = pearsonr(df["confidence_semantic"], df["correct"])

spearman_sc = spearmanr(df["confidence_sc"], df["correct"])
spearman_sem = spearmanr(df["confidence_semantic"], df["correct"])

pearson_sc, pearson_sem, spearman_sc, spearman_sem

# Calibration Bins
# Purpose: Analyze confidence calibration.

def calibration_bins(conf, correct, bins=5):
    temp = pd.DataFrame({"conf": conf, "correct": correct})
    temp["bin"] = pd.cut(temp["conf"], bins=bins)
    return temp.groupby("bin")["correct"].mean()

cal_sc = calibration_bins(df["confidence_sc"], df["correct"])
cal_sem = calibration_bins(df["confidence_semantic"], df["correct"])

cal_sc, cal_sem

# Confidence vs Correctness Plot
# Purpose: Visual diagnostic for miscalibration.

plt.figure(figsize=(6,4))
plt.scatter(df["confidence_semantic"], df["correct"], alpha=0.5)
plt.xlabel("Semantic Confidence")
plt.ylabel("Correctness (1=True)")
plt.title("Semantic Confidence vs Correctness")
plt.show()

# Identify High-Confidence Errors
# Purpose: Core failure cases (research highlight).

high_conf_errors = df[
    (df["confidence_semantic"] > 0.75) &
    (df["correct"] == 0)
]

high_conf_errors[["question", "final_answer", "confidence_semantic", "category"]].head(10)

# Failure Rate by Category
# Purpose: Understand domain-specific weaknesses.

category_summary = df.groupby("category").agg(
    accuracy=("correct", "mean"),
    avg_confidence=("confidence_semantic", "mean")
)

category_summary

# Failure Type Annotation
# Purpose: Qualitative failure taxonomy.

df["failure_type"] = df.apply(
    lambda x: "High-Confidence Error" if (x["confidence_semantic"] > 0.75 and x["correct"] == 0)
    else "Low-Confidence Correct" if (x["confidence_semantic"] < 0.4 and x["correct"] == 1)
    else "Normal",
    axis=1
)

df["failure_type"].value_counts()

# Example Failure Cases
# Purpose: Evidence table for paper.

df[df["failure_type"] == "High-Confidence Error"][
    ["question", "final_answer", "confidence_semantic", "category"]
].head(5)

# Save Results
# Purpose: Reproducibility & sharing.

df.to_csv("full_llm_failure_results.csv", index=False)
category_summary.to_csv("category_summary.csv")